name: BSD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  freebsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        release: "14.3" 
        usesh: true
        prepare: |
          # pkg-static update
          # pkg-static upgrade -y pkg
          pkg install -y ghc hs-cabal-install

        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          sysctl hw.model
          sysctl hw.ncpu
          sysctl hw.physmem
          sysctl hw.usermem

          ghc --version
          cabal --version

          cabal update
          cabal build all --enable-tests --dry-run
          cabal build all --enable-tests
          cabal test all --enable-tests --test-show-details=direct

  netbsd:
    name: NetBSD
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test in NetBSD
      id: test
      uses: vmactions/netbsd-vm@v1
      with:
        release: "10.1"
        usesh: true
        prepare: |
          /usr/sbin/pkg_add ghc cabal-install

        run: |
          cd $GITHUB_WORKSPACE;
          pwd
          ls -lah
          whoami
          env
          /sbin/sysctl hw.model
          /sbin/sysctl hw.ncpu
          /sbin/sysctl hw.physmem
          /sbin/sysctl hw.usermem
          /usr/bin/vmstat

          ghc --version
          cabal --version

          cabal update
          cabal build all --enable-tests --dry-run
          cabal build all --enable-tests
          cabal test all --enable-tests --test-show-details=direct
